#### 1.Create a 1D array using arange().
   - Use the flip() function to reverse the order of elements in a 1D array.
   - Achieve the same above output without using flip().


In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
# With using flip()function
reverse_arr=np.flip(arr)
reverse_arr

array([5, 4, 3, 2, 1])

In [8]:
# Without using flip function
### Start = (At last); Stop = (At Beginning); Step = -VE 1 Step  at a time.
arr[::-1] 

array([5, 4, 3, 2, 1])

In [9]:
arr[len(arr)::-1]

array([5, 4, 3, 2, 1])

In [14]:
### START = -1; END = -7; STEP = BACKWARD STEP OF 1 (OR -1 STEPS AT A TIME)
arr[-1:-7:-1]

array([5, 4, 3, 2, 1])

b. 
- Create a boolean array indicating which elements of the above 1D array are greater than 3.
- Replace all even numbers in the array with -1


In [17]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [18]:
Greater_3 = arr > 3
Greater_3

array([False, False, False,  True,  True])

In [21]:
# Replacing all even numbers with -1
arr_negative = np.where(arr % 2 == 0, -1,arr)
arr_negative

array([ 1, -1,  3, -1,  5])

#### 2.a. Generate a 2D array with random elements. 
   - Transpose the array.
   - Flatten the array 


In [22]:
arr_1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
arr_1

array([[ 1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16]])

In [24]:
arr_1.ndim #Checking the dimension of the array

2

In [25]:
arr_1.transpose()

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 5, 16]])

In [30]:
flattened_arr=arr_1.flatten() #It arranges the data in 1D Array
flattened_arr

array([ 1,  2,  3,  4,  5, 12, 13, 14, 15, 16])

In [ ]:
# Inserting 99 at the index 2
array_99 = np.insert(flattened_arr, 2, 99) #assigning at 2nd index i.e 99
array_99

In [35]:
# Adding an element
array_100=np.append(array_99, 100) #Adding an element at last i.e 100
array_100

array([  1,   2,  99,   3,   4,   5,  12,  13,  14,  15,  16, 100])

In [39]:
array_delete=np.delete(array_100, 6) #it removed 6th indexing value
array_delete

array([  1,   2,  99,   3,   4,   5,  13,  14,  15,  16, 100])

 #### a. Create a 2D array. Iterate through the elements of the array and print elements using both nditer() and for loop.
b. Generate two arrays with random float elements in it.
 - perform all python operations (* + - / % //).
 - Also apply all mathematical functions on the two arrays.



In [41]:
arr_2d = np.array([[1,2,3,4,5,6],[67,68,69,65,64,61],[43,44,45,46,47,48]])
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [67, 68, 69, 65, 64, 61],
       [43, 44, 45, 46, 47, 48]])

In [46]:
for element in np.nditer(arr_2d):
    print(element,end = " ")#to get the loop into horizontal i used end fun    

1 2 3 4 5 6 67 68 69 65 64 61 43 44 45 46 47 48 

In [53]:
arr_1 = np.random.rand(6, 4)
arr_2 = np.random.rand(6, 4)
arr_1

array([[0.12325527, 0.69137512, 0.19360299, 0.70182385],
       [0.03676345, 0.43784029, 0.64255518, 0.11143619],
       [0.29950092, 0.61952658, 0.6291954 , 0.69160822],
       [0.45289959, 0.47421948, 0.39247397, 0.86317398],
       [0.20702236, 0.50963123, 0.34320515, 0.96893457],
       [0.75550374, 0.86984457, 0.63953317, 0.32474613]])

In [54]:
arr_2

array([[0.63661418, 0.14542606, 0.38956401, 0.99447363],
       [0.06630298, 0.69251195, 0.04010579, 0.36790081],
       [0.00639858, 0.00441085, 0.24935535, 0.54684268],
       [0.48248042, 0.66101581, 0.75966432, 0.50485245],
       [0.77063514, 0.50893953, 0.64184025, 0.34429235],
       [0.93199363, 0.23855821, 0.84804331, 0.01277321]])

In [55]:
arr_1 + arr_2 #Adding the arrays

array([[0.75986945, 0.83680119, 0.583167  , 1.69629749],
       [0.10306643, 1.13035224, 0.68266096, 0.479337  ],
       [0.3058995 , 0.62393743, 0.87855075, 1.2384509 ],
       [0.93538001, 1.13523529, 1.15213829, 1.36802642],
       [0.9776575 , 1.01857076, 0.9850454 , 1.31322692],
       [1.68749738, 1.10840278, 1.48757648, 0.33751935]])

In [56]:
arr_1 - arr_2 #subtracting arrays

array([[-0.51335891,  0.54594906, -0.19596102, -0.29264978],
       [-0.02953953, -0.25467166,  0.60244939, -0.25646462],
       [ 0.29310234,  0.61511573,  0.37984005,  0.14476554],
       [-0.02958083, -0.18679633, -0.36719034,  0.35832153],
       [-0.56361278,  0.0006917 , -0.2986351 ,  0.62464221],
       [-0.17648989,  0.63128636, -0.20851014,  0.31197292]])

In [57]:
arr_1 / arr_2 #dividing arrays

array([[  0.19361063,   4.75413484,   0.49697349,   0.70572394],
       [  0.55447659,   0.63224944,  16.02150718,   0.30289737],
       [ 46.80741312, 140.45514461,   2.52328815,   1.26472977],
       [  0.9386901 ,   0.71741019,   0.51664132,   1.70975495],
       [  0.26863862,   1.0013591 ,   0.53472051,   2.8142785 ],
       [  0.81063187,   3.64625712,   0.75412796,  25.42399554]])

In [58]:
arr_1 // arr_2 #floor division gives the Round off value

array([[  0.,   4.,   0.,   0.],
       [  0.,   0.,  16.,   0.],
       [ 46., 140.,   2.,   1.],
       [  0.,   0.,   0.,   1.],
       [  0.,   1.,   0.,   2.],
       [  0.,   3.,   0.,  25.]])

In [61]:
np.sin(arr_1) #Mathematical functions

array([[0.12294343, 0.63759714, 0.19239581, 0.64561158],
       [0.03675517, 0.42398447, 0.59924299, 0.1112057 ],
       [0.29504338, 0.58064979, 0.58849443, 0.63777669],
       [0.43757463, 0.45664419, 0.38247545, 0.75990956],
       [0.20554675, 0.48785537, 0.33650704, 0.82428296],
       [0.68565544, 0.7642287 , 0.59682093, 0.3190682 ]])

In [62]:
np.cos(arr_1)

array([[0.99241368, 0.77036997, 0.98131741, 0.76366596],
       [0.9993243 , 0.90566946, 0.8005672 , 0.99379741],
       [0.95548386, 0.81415344, 0.80850127, 0.77022133],
       [0.8991821 , 0.88964941, 0.92396565, 0.65002881],
       [0.9786473 , 0.87292447, 0.94168095, 0.56617807],
       [0.72792624, 0.64494534, 0.80237446, 0.94773176]])

In [63]:
np.sin(arr_2)

array([[0.59447627, 0.14491401, 0.37978513, 0.83847224],
       [0.06625441, 0.6384725 , 0.04009504, 0.35965751],
       [0.00639854, 0.00441084, 0.2467793 , 0.51999294],
       [0.46397787, 0.61391902, 0.68867809, 0.4836783 ],
       [0.69659107, 0.48725145, 0.59867049, 0.33753064],
       [0.80281021, 0.23630191, 0.74998758, 0.01277287]])

In [64]:
np.sin(arr_2)

array([[0.59447627, 0.14491401, 0.37978513, 0.83847224],
       [0.06625441, 0.6384725 , 0.04009504, 0.35965751],
       [0.00639854, 0.00441084, 0.2467793 , 0.51999294],
       [0.46397787, 0.61391902, 0.68867809, 0.4836783 ],
       [0.69659107, 0.48725145, 0.59867049, 0.33753064],
       [0.80281021, 0.23630191, 0.74998758, 0.01277287]])

In [65]:
np.tan(arr_1)

array([[0.12388325, 0.82765056, 0.1960587 , 0.84541097],
       [0.03678002, 0.46814483, 0.74852303, 0.11189977],
       [0.3087895 , 0.71319454, 0.72788312, 0.82804341],
       [0.48663628, 0.51328556, 0.41394986, 1.16903982],
       [0.2100315 , 0.55887466, 0.35734719, 1.45587227],
       [0.94192984, 1.18495111, 0.74381846, 0.33666509]])

In [72]:
np.tan(arr_2)

array([[0.7392943 , 0.14646   , 0.41054535, 1.53863841],
       [0.06640031, 0.82956792, 0.04012731, 0.38545014],
       [0.00639867, 0.00441088, 0.25465535, 0.60876944],
       [0.52376763, 0.77773387, 0.94981274, 0.55261993],
       [0.97090143, 0.55796727, 0.74740814, 0.35857371],
       [1.34646686, 0.24318911, 1.13385052, 0.01277391]])

In [78]:
np.log(arr_1)

array([[-2.09349769, -0.36907274, -1.64194567, -0.35407283],
       [-3.30325111, -0.82590107, -0.44230259, -2.19430314],
       [-1.20563779, -0.47879967, -0.46331341, -0.36873564],
       [-0.79208483, -0.74608503, -0.93528505, -0.14713901],
       [-1.57492848, -0.67406789, -1.06942691, -0.0315582 ],
       [-0.28037054, -0.13944074, -0.44701679, -1.12471153]])

In [80]:
np.abs(arr_2) #applying modulus to negative values and making them positive

array([[2.09349769, 0.36907274, 1.64194567, 0.35407283],
       [3.30325111, 0.82590107, 0.44230259, 2.19430314],
       [1.20563779, 0.47879967, 0.46331341, 0.36873564],
       [0.79208483, 0.74608503, 0.93528505, 0.14713901],
       [1.57492848, 0.67406789, 1.06942691, 0.0315582 ],
       [0.28037054, 0.13944074, 0.44701679, 1.12471153]])

In [81]:
np.exp(arr_1)

array([[1.13117314, 1.99645902, 1.21361437, 2.01742885],
       [1.03744758, 1.54935744, 1.90133292, 1.11788241],
       [1.34918529, 1.8580482 , 1.87610047, 1.99692444],
       [1.57286625, 1.6067596 , 1.48063933, 2.37067322],
       [1.23001007, 1.6646772 , 1.40945788, 2.6351354 ],
       [2.12868357, 2.38653988, 1.89559575, 1.38367933]])

#### Create a random NumPy array. Generate mean, mode, median, variance and standard deviation of that array.
Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays


In [88]:
arr_3=np.random.randint(4,400,size=(4,5))
arr_3

array([[260, 329, 266, 141,  28],
       [134, 312, 209, 181, 294],
       [139, 373, 147, 135, 245],
       [115, 148, 268, 317,  67]])

In [101]:
np.mean(arr_3)

205.4

In [98]:
a=arr_3.flatten()
a

array([260, 329, 266, 141,  28, 134, 312, 209, 181, 294, 139, 373, 147,
       135, 245, 115, 148, 268, 317,  67])

In [102]:
sum(a)/len(a) #checking the mean it is making flatten and calculating

205.4

In [104]:
np.var(arr_3)

8594.84

In [106]:
np.std(arr_3)

92.70835992508982

In [107]:
#std=sqrt(var)
92.7083599250892*92.7083599250892

8594.839999999886

In [110]:
np.median(arr_3) 
#if the no of terms are odd then median will be the middle term.
#if the no of terms are even then median will be average of 
#(n/2 th term and (n/2 +1) th term

195.0

In [112]:
arr_4=np.array([1,2,3,4,5,6,7,8])
arr_5=np.array([10,20,30,40,50,60,70,80])
arr_4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
arr_5

array([10, 20, 30, 40, 50, 60, 70, 80])