**Exercise: Given an array [1, -10, 2, 3, 0, 6], print the array in this order [0, 6, -10, 2, 1, 3]**

In [1]:
import numpy as np
arr=np.array([1,-10,2,3,0,6])
print(arr[[4,5,1,2,0,3]])

[  0   6 -10   2   1   3]


#### Updating Data in Numpy Array

In [3]:
# Updating value in the array

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size=(5, 4))

print("Original Array: \n", arr)

Original Array: 
 [[39 63  6 89]
 [24  6 25 58]
 [88 72 34 36]
 [65 73 69 50]
 [40 86 83 58]]


In [5]:
arr[1,1]

6

In [7]:
arr[1, 1] = 170

print("Updated Array: \n", arr)

Updated Array: 
 [[ 39  63   6  89]
 [ 24 170  25  58]
 [ 88  72  34  36]
 [ 65  73  69  50]
 [ 40  86  83  58]]


## Numpy Flatten and Ravel

In [9]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[32 11 28 25 13 11 32 30 10 11]
 [24 31 35 39 39 24 34 17 21 26]
 [33 28 12 21 22 38 33 38 20 30]
 [27 27 18 30 11 23 32 34 38 17]
 [30 25 28 23 19 17 11 24 15 34]]
Shape:  (5, 10)


In [15]:
arr[-1][-3] = 1000000

In [17]:
k1

array([32, 11, 28, 25, 13, 11, 32, 30, 10, 11, 24, 31, 35, 39, 39, 24, 34,
       17, 21, 26, 33, 28, 12, 21, 22, 38, 33, 38, 20, 30, 27, 27, 18, 30,
       11, 23, 32, 34, 38, 17, 30, 25, 28, 23, 19, 17, 11, 24, 15, 34])

In [19]:
k2

array([     32,      11,      28,      25,      13,      11,      32,
            30,      10,      11,      24,      31,      35,      39,
            39,      24,      34,      17,      21,      26,      33,
            28,      12,      21,      22,      38,      33,      38,
            20,      30,      27,      27,      18,      30,      11,
            23,      32,      34,      38,      17,      30,      25,
            28,      23,      19,      17,      11, 1000000,      15,
            34])

In [11]:
k1= arr.flatten()
k1

array([32, 11, 28, 25, 13, 11, 32, 30, 10, 11, 24, 31, 35, 39, 39, 24, 34,
       17, 21, 26, 33, 28, 12, 21, 22, 38, 33, 38, 20, 30, 27, 27, 18, 30,
       11, 23, 32, 34, 38, 17, 30, 25, 28, 23, 19, 17, 11, 24, 15, 34])

In [13]:
k2= arr.ravel()
k2

array([32, 11, 28, 25, 13, 11, 32, 30, 10, 11, 24, 31, 35, 39, 39, 24, 34,
       17, 21, 26, 33, 28, 12, 21, 22, 38, 33, 38, 20, 30, 27, 27, 18, 30,
       11, 23, 32, 34, 38, 17, 30, 25, 28, 23, 19, 17, 11, 24, 15, 34])

In [10]:
arr[0,2] =1340000

In [13]:
arr

array([[     17,      38, 1340000,      27,      14,      26,      28,
             13,      18,      21],
       [     22,      36,      38,      35,      38,      37,      38,
             35,      38,      22],
       [     34,      16,      17,      19,      19,      27,      38,
             11,      37,      27],
       [     25,      22,      17,      12,      17,      17,      39,
             14,      28,      28],
       [     10,      20,      36,      19,      30,      27,      20,
             21,      33,      28]])

In [12]:
print(arr)

[[     17      38 1340000      27      14      26      28      13      18
       21]
 [     22      36      38      35      38      37      38      35      38
       22]
 [     34      16      17      19      19      27      38      11      37
       27]
 [     25      22      17      12      17      17      39      14      28
       28]
 [     10      20      36      19      30      27      20      21      33
       28]]


In [14]:
print(k1)

[17 38 27 27 14 26 28 13 18 21 22 36 38 35 38 37 38 35 38 22 34 16 17 19
 19 27 38 11 37 27 25 22 17 12 17 17 39 14 28 28 10 20 36 19 30 27 20 21
 33 28]


In [15]:
print(k2)

[     17      38 1340000      27      14      26      28      13      18
      21      22      36      38      35      38      37      38      35
      38      22      34      16      17      19      19      27      38
      11      37      27      25      22      17      12      17      17
      39      14      28      28      10      20      36      19      30
      27      20      21      33      28]


#### Look's like both are performing fatten operation on the array data. But is there any difference between two functions?

ravel is like mirror view of orginal array if org array changes ravel array changes

flatten will take different memory location

#### Observation
Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

**Task : Copy() vs View()**

## Iterating over Numpy Array

#### Iterating over a 1 Dimensional Array

In [23]:
# Randomly generate an array containing values in the range of 10 to 39
import numpy as np

arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [36 13 14 39 24 19 19 15 11 23]
Shape:  (10,)


In [25]:
# Looping over items in the array
for i in arr1d:
    print(i)

36
13
14
39
24
19
19
15
11
23


In [27]:
arr1d

array([36, 13, 14, 39, 24, 19, 19, 15, 11, 23])

In [29]:
# Looping over indexes in the array
for i in range(arr1d.size):
    print(i,"---",arr1d[i])

0 --- 36
1 --- 13
2 --- 14
3 --- 39
4 --- 24
5 --- 19
6 --- 19
7 --- 15
8 --- 11
9 --- 23


In [35]:
arr1d

array([36, 13, 14, 39, 24, 19, 19, 15, 11, 23])

In [39]:
# print elements at even indexes
# o/p :  14,29,26,37,30

for i in range(arr1d.size):
    if i%2==0:
        print(arr1d[i])

36
14
24
19
11


In [41]:
# print even elements in the array
for i in arr1d:
    if i%2==0:
        print(i)

36
14
24


In [45]:
#using Boolean indexing
arr1d

array([36, 13, 14, 39, 24, 19, 19, 15, 11, 23])

In [51]:
arr1d[arr1d%2==0]

array([36, 14, 24])

In [49]:
#np.where(a%2==0,a,0)

## Iterating over a 2 Dimensional Array

In [53]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
import numpy as np
arr2d = np.random.randint(10, 40, size = (5, 10))
print("Numpy Array: \n", arr2d)
print("Shape: ", arr2d.shape)

Numpy Array: 
 [[20 38 31 38 38 32 13 19 10 18]
 [35 24 16 25 31 12 34 26 25 10]
 [26 11 21 28 25 14 33 32 14 20]
 [36 39 35 14 14 32 27 12 23 24]
 [14 23 30 20 34 20 32 34 12 30]]
Shape:  (5, 10)


### looping with elements

In [68]:
arr2d

array([[20, 38, 31, 38, 38, 32, 13, 19, 10, 18],
       [35, 24, 16, 25, 31, 12, 34, 26, 25, 10],
       [26, 11, 21, 28, 25, 14, 33, 32, 14, 20],
       [36, 39, 35, 14, 14, 32, 27, 12, 23, 24],
       [14, 23, 30, 20, 34, 20, 32, 34, 12, 30]])

In [72]:
#o(n)
for i in arr2d.ravel():
    print(i,end=" ")

20 38 31 38 38 32 13 19 10 18 35 24 16 25 31 12 34 26 25 10 26 11 21 28 25 14 33 32 14 20 36 39 35 14 14 32 27 12 23 24 14 23 30 20 34 20 32 34 12 30 

In [66]:
#t.c -- o(n2)
for i in arr2d:
    for j in i:
        print(j,end=" ")
    print()
    print("---")

20 38 31 38 38 32 13 19 10 18 
---
35 24 16 25 31 12 34 26 25 10 
---
26 11 21 28 25 14 33 32 14 20 
---
36 39 35 14 14 32 27 12 23 24 
---
14 23 30 20 34 20 32 34 12 30 
---


In [58]:
for i in temp:
    for j in i:
        print(j.upper())

MOM
RAMYA
KHAN
GIRIJA


In [61]:
for i in temp.ravel():
    print(i.upper())

MOM
RAMYA
KHAN
GIRIJA


In [62]:
temp

array([['mom', 'ramya'],
       ['khan', 'girija']], dtype='<U6')

In [67]:
np.char.upper(temp)

array([['MOM', 'RAMYA'],
       ['KHAN', 'GIRIJA']], dtype='<U6')

In [53]:
# Looping over rows in the 2d array
for i in arr2d:
    print(i)
    print("----")

[20 35 33 14 13 40 17 15 18 23]
----
[14 26 28 23 39 29 36 39 39 40]
----
[36 29 27 35 12 39 22 13 32 23]
----
[26 27 29 31 31 19 33 26 39 18]
----
[29 19 39 24 26 28 29 25 17 24]
----


In [52]:
# Looping over rows in the 2d array
for i in arr2d:
    for j in i:
        print(j)
    print("----")

18
33
31
12
11
38
15
13
16
21
----
12
24
26
21
37
27
34
37
37
38
----
34
27
25
33
10
37
20
11
30
21
----
24
25
27
29
29
17
31
24
37
16
----
27
17
37
22
24
26
27
23
15
22
----


In [35]:
#element wise iteration in 2d ararys
import numpy as np
for i in arr2d:
    for j in i:
        print(j)
    print("---")

26
26
29
37
16
22
32
38
17
28
---
34
31
24
13
28
36
14
38
11
15
---
11
10
29
19
22
24
19
30
22
37
---
10
11
36
27
32
34
25
26
33
20
---
35
24
31
38
12
12
35
33
18
27
---


### looping with indexing

In [74]:
import numpy as np
arr2d = np.array([[33, 29, 18, 13, 33, 25, 27, 18, 1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, 2],
       [16, 4, 34, 34,5, 39, 12, 22, 3, 14],
       [39, 2, 19, 13, 17, 31, 28, 12,5, 37],
       [30, 33, 5, 29, 19, 20, 35, 13, 23, 11]])
t=arr2d.shape
t

(5, 10)

In [84]:
#iterating using indexing in 2d arrays (using only rows)
rows=t[0]
cols=t[1]
for i in range(rows):
    for j in range(cols):
        print(arr2d[i,j],end=" ")

33 29 18 13 33 25 27 18 1 39 36 11 14 34 38 31 11 34 38 2 16 4 34 34 5 39 12 22 3 14 39 2 19 13 17 31 28 12 5 37 30 33 5 29 19 20 35 13 23 11 

In [66]:
arr2d

array([[33, 29, 18, 13, 33, 25, 27, 18,  1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38,  2],
       [16,  4, 34, 34,  5, 39, 12, 22,  3, 14],
       [39,  2, 19, 13, 17, 31, 28, 12,  5, 37],
       [30, 33,  5, 29, 19, 20, 35, 13, 23, 11]])

**iterating elements in 2d arrays using only one for loop with ravel**

In [73]:
# Looping over each item in the 2d array
for i in arr2d.ravel():
    print(i, end=" ")

33 29 18 13 33 25 27 18 1 39 36 11 14 34 38 31 11 34 38 2 16 4 34 34 5 39 12 22 3 14 39 2 19 13 17 31 28 12 5 37 30 33 5 29 19 20 35 13 23 11 

In [74]:
# Looping over each even element in the 2d array
for i in arr2d.ravel():
    if i%2==0:
        print(i, end=" ")

18 18 36 14 34 38 34 38 2 16 4 34 34 12 22 14 2 28 12 30 20 

In [77]:
#iterating using indexing in 2d arrays (using only rows and columns)
rows=t[0]
cols=t[1]
for i in range(rows):
    for j in range(cols):
        if arr2d[i][j]%2==0:
            print(arr2d[i][j],end=" ")

18 18 36 14 34 38 34 38 2 16 4 34 34 12 22 14 2 28 12 30 20 

In [78]:
arr2d

array([[33, 29, 18, 13, 33, 25, 27, 18,  1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38,  2],
       [16,  4, 34, 34,  5, 39, 12, 22,  3, 14],
       [39,  2, 19, 13, 17, 31, 28, 12,  5, 37],
       [30, 33,  5, 29, 19, 20, 35, 13, 23, 11]])

# 30-sep-2024

# T.C= O(N2)

In [1]:
import numpy as np
import random

In [7]:
a = np.random.randint(1,50,(5,10))
a

array([[ 1,  1, 39,  1,  5, 27, 30, 10, 44, 29],
       [ 1, 17, 20, 29, 36,  7, 14, 37, 25, 30],
       [16, 10, 47, 10, 32, 21,  9, 48, 13, 16],
       [10, 21, 17, 44, 41, 39, 45, 33,  9, 16],
       [37, 29,  9, 34, 10, 41, 18,  6, 47,  3]])

In [11]:
a

array([[ 1,  1, 39,  1,  5, 27, 30, 10, 44, 29],
       [ 1, 17, 20, 29, 36,  7, 14, 37, 25, 30],
       [16, 10, 47, 10, 32, 21,  9, 48, 13, 16],
       [10, 21, 17, 44, 41, 39, 45, 33,  9, 16],
       [37, 29,  9, 34, 10, 41, 18,  6, 47,  3]])

In [19]:
# when elements itself are even replace with hurray otherwise oops
for i in a:
    for j in i:
        if j%2==0:
            print(j)

30
10
44
20
36
14
30
16
10
10
32
48
16
10
44
16
34
10
18
6


In [23]:
# when elements itself are even replace with hurray otherwise oops
for i in a:
    for j in i:
        if j%2==0:
           print(j)

30
10
44
20
36
14
30
16
10
10
32
48
16
10
44
16
34
10
18
6


In [45]:
a =  a.astype('str')
a

array([['1', '1', '39', '1', '5', '27', '30', '10', '44', '29'],
       ['1', '17', '20', '29', '36', '7', '14', '37', '25', '30'],
       ['16', '10', '47', '10', '32', '21', '9', '48', '13', '16'],
       ['10', '21', '17', '44', '41', '39', '45', '33', '9', '16'],
       ['37', '29', '9', '34', '10', '41', '18', '6', '47', '3']],
      dtype='<U11')

In [49]:
a

array([['1', '1', '39', '1', '5', '27', '30', '10', '44', '29'],
       ['1', '17', '20', '29', '36', '7', '14', '37', '25', '30'],
       ['16', '10', '47', '10', '32', '21', '9', '48', '13', '16'],
       ['10', '21', '17', '44', '41', '39', '45', '33', '9', '16'],
       ['37', '29', '9', '34', '10', '41', '18', '6', '47', '3']],
      dtype='<U11')

In [51]:
# when elements itself are even replace with hurray otherwise oops
t = a.shape
x= t[0]
y= t[1]
for i in range(x):
    for j in range(y):
        if int(a[i,j])%2==0:
            a[i,j] = 'hurray'
        else:
            a[i,j] = 'oops'

In [72]:
#a. when cols indexes are even  replace with hurray otherwise oops
a = np.random.randint(1,50,(5,10))
a= a.astype('str')
print(a)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if j%2==0:
            a[i,j]='hurray'
        else:
            a[i,j]='oops'

[['36' '48' '36' '8' '6' '24' '6' '25' '49' '25']
 ['38' '31' '3' '30' '2' '39' '49' '9' '9' '25']
 ['30' '5' '7' '44' '7' '37' '5' '17' '22' '49']
 ['15' '1' '44' '11' '36' '9' '46' '31' '19' '47']
 ['43' '18' '34' '13' '37' '44' '28' '34' '10' '31']]


In [70]:
a

array([['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops'],
       ['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops'],
       ['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops'],
       ['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops'],
       ['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops']], dtype='<U11')

In [74]:
#b. when rows indexes are even  cols indexes are even replace with hurray otherwise oops
a = np.random.randint(1,50,(5,10))
a= a.astype('str')
print(a)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if (i%2==0) and (j%2==0):
            a[i,j]='hurray'
        else:
            a[i,j]='oops'

[['7' '18' '17' '34' '4' '26' '7' '27' '12' '20']
 ['11' '27' '32' '4' '22' '42' '23' '6' '48' '9']
 ['1' '44' '22' '3' '28' '6' '30' '37' '35' '31']
 ['38' '30' '15' '25' '28' '43' '25' '40' '26' '11']
 ['1' '47' '38' '12' '36' '15' '48' '41' '17' '7']]


In [76]:
a

array([['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops'],
       ['oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'oops', 'oops'],
       ['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops'],
       ['oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'oops', 'oops'],
       ['hurray', 'oops', 'hurray', 'oops', 'hurray', 'oops', 'hurray',
        'oops', 'hurray', 'oops']], dtype='<U11')

In [ ]:
#  0 (n2)

In [79]:
a= np.random.randint(100,200,(3,4))

In [81]:
a

array([[101, 107, 198, 184],
       [172, 149, 148, 169],
       [116, 147, 169, 167]])

In [95]:
#Task : elipsis operator ...
#o(n)
for i in np.nditer(a.ravel(),op_flags=['readwrite']):
        if i%2==0:
            i[...]= 0
        else:
            i[...]= -1

a

array([[-1, -1,  0,  0],
       [ 0, -1,  0, -1],
       [ 0, -1, -1, -1]])

In [ ]:
198
184
172
148
116

In [90]:
for i in np.nditer(arr2d):
    print(i)

131
158
105
195
198
187
100
153
171
109
170
105


In [101]:
for i in np.nditer(arr2d,op_flags=['readwrite']):
    if i%2==0:
        i[...]=0
    else:
        i[...]=-1

In [99]:
arr2d

array([[-1,  0, -1, -1],
       [ 0, -1,  0, -1],
       [-1, -1,  0, -1]])

In [100]:
arr2d

array([[-1,  0, -1, -1],
       [ 0, -1,  0, -1],
       [-1, -1,  0, -1]])

**iterating elements in 2d arrays using only one for loop with**  `np.nditer()`

# updating when using nditer

In [53]:

for item in np.nditer(arr2d):
    if item<5:
        item[...] = -1 #[...] ellipsis explore this ... in python
        
print("Updated Array", arr2d)

ValueError: assignment destination is read-only

In [70]:
print("Original Array: ", arr2d)

for item in np.nditer(arr2d, op_flags=['readwrite']):
    if item <5:
        item[...] = -1
        
print("Updated Array", arr2d)

Original Array:  [[28 30 20 34 10 31 22 34 31 32]
 [23 26 11 33 32 21 30 31 38 18]
 [27 12 36 17 20 35 26 12 18 22]
 [20 15 18 39 13 27 39 35 16 17]
 [19 30 33 18 24 26 38 29 32 18]]
Updated Array [[28 30 20 34 10 31 22 34 31 32]
 [23 26 11 33 32 21 30 31 38 18]
 [27 12 36 17 20 35 26 12 18 22]
 [20 15 18 39 13 27 39 35 16 17]
 [19 30 33 18 24 26 38 29 32 18]]


## questn: when element is <5 replce with -1
---

## with two for loops

In [28]:
import numpy as np
a = np.array([[33, 29, 18, 13, 33, 25, 27, 18, 1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, 2],
       [16, 4, 34, 34,5, 39, 12, 22, 3, 14],
       [39, 2, 19, 13, 17, 31, 28, 12,5, 37],
       [30, 33, 5, 29, 19, 20, 35, 13, 23, 11]])

In [30]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i][j] <5:
            a[i][j]=-1
            
a

array([[33, 29, 18, 13, 33, 25, 27, 18, -1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, -1],
       [16, -1, 34, 34,  5, 39, 12, 22, -1, 14],
       [39, -1, 19, 13, 17, 31, 28, 12,  5, 37],
       [30, 33,  5, 29, 19, 20, 35, 13, 23, 11]])

## with single for loop

In [110]:
import numpy as np
a = np.array([[33, 29, 18, 13, 33, 25, 27, 18, 1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, 2],
       [16, 4, 34, 34,5, 39, 12, 22, 3, 14],
       [39, 2, 19, 13, 17, 31, 28, 12,5, 37],
       [30, 33, 5, 29, 19, 20, 35, 13, 23, 11]])

In [111]:
for i in np.nditer(a,op_flags=["readwrite"]):
    if i<5:
        i[...]=-1
a

array([[33, 29, 18, 13, 33, 25, 27, 18, -1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, -1],
       [16, -1, 34, 34,  5, 39, 12, 22, -1, 14],
       [39, -1, 19, 13, 17, 31, 28, 12,  5, 37],
       [30, 33,  5, 29, 19, 20, 35, 13, 23, 11]])

## without uisng for loop (boolean indexing)

In [112]:
import numpy as np
a = np.array([[33, 29, 18, 13, 33, 25, 27, 18, 1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, 2],
       [16, 4, 34, 34,5, 39, 12, 22, 3, 14],
       [39, 2, 19, 13, 17, 31, 28, 12,5, 37],
       [30, 33, 5, 29, 19, 20, 35, 13, 23, 11]])
print(a)

[[33 29 18 13 33 25 27 18  1 39]
 [36 11 14 34 38 31 11 34 38  2]
 [16  4 34 34  5 39 12 22  3 14]
 [39  2 19 13 17 31 28 12  5 37]
 [30 33  5 29 19 20 35 13 23 11]]


In [113]:
a[a<5]=-1
print(a)

[[33 29 18 13 33 25 27 18 -1 39]
 [36 11 14 34 38 31 11 34 38 -1]
 [16 -1 34 34  5 39 12 22 -1 14]
 [39 -1 19 13 17 31 28 12  5 37]
 [30 33  5 29 19 20 35 13 23 11]]


## without uisng for loop (where function) 

In [114]:
import numpy as np
a = np.array([[33, 29, 18, 13, 33, 25, 27, 18, 1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, 2],
       [16, 4, 34, 34,5, 39, 12, 22, 3, 14],
       [39, 2, 19, 13, 17, 31, 28, 12,5, 37],
       [30, 33, 5, 29, 19, 20, 35, 13, 23, 11]])
print(a)

[[33 29 18 13 33 25 27 18  1 39]
 [36 11 14 34 38 31 11 34 38  2]
 [16  4 34 34  5 39 12 22  3 14]
 [39  2 19 13 17 31 28 12  5 37]
 [30 33  5 29 19 20 35 13 23 11]]


In [115]:
np.where(a<5,-1,a)

array([[33, 29, 18, 13, 33, 25, 27, 18, -1, 39],
       [36, 11, 14, 34, 38, 31, 11, 34, 38, -1],
       [16, -1, 34, 34,  5, 39, 12, 22, -1, 14],
       [39, -1, 19, 13, 17, 31, 28, 12,  5, 37],
       [30, 33,  5, 29, 19, 20, 35, 13, 23, 11]])

In [116]:
np.where(a<5,"hurray","oops")

array([['oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'hurray', 'oops'],
       ['oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'oops', 'hurray'],
       ['oops', 'hurray', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'hurray', 'oops'],
       ['oops', 'hurray', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'oops', 'oops'],
       ['oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops', 'oops',
        'oops', 'oops']], dtype='<U6')

**Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all numbers which are divisible by 5 with python and which are not divsible by 5 replace them with java.**

1. using two for loops
2. using one loop(nditer)
3. without using loop 
a.(boolean indexing)
b.(where)

# 3d arrays

In [97]:
a = np.random.randint(1, 10, (3,4,5))
a

array([[[7, 9, 7, 9, 7],
        [8, 7, 8, 2, 2],
        [9, 6, 7, 3, 8],
        [3, 5, 4, 5, 6]],

       [[4, 5, 9, 8, 4],
        [7, 9, 2, 4, 6],
        [4, 2, 6, 7, 2],
        [6, 2, 5, 7, 7]],

       [[5, 3, 8, 6, 6],
        [3, 7, 6, 6, 5],
        [9, 6, 6, 5, 7],
        [5, 2, 4, 3, 1]]])

In [111]:
for i in a:
    for j in i:
        for k in j:
            print(k)

7
9
7
9
7
8
7
8
2
2
9
6
7
3
8
3
5
4
5
6
4
5
9
8
4
7
9
2
4
6
4
2
6
7
2
6
2
5
7
7
5
3
8
6
6
3
7
6
6
5
9
6
6
5
7
5
2
4
3
1


In [ ]:
# create a 3d array  shape is (2,3,4)
#a. filter out even elements
#b. when even 2d array even rows even cols -- replace them with -1 otherwise 0
#c. do above  a questn one by using np.nditer()

In [113]:
a= np.random.randint(1,50,(2,3,4))
a

array([[[41, 49, 33, 29],
        [17, 16, 18,  3],
        [30, 36, 43, 18]],

       [[20, 29, 15, 34],
        [23, 37, 38,  8],
        [35, 12,  9,  8]]])

In [119]:
#a. element wise iterations
for i in a:
    for j in i:
        for k in j:
            if k%2==0:
                print(k)

16
18
30
36
18
20
34
38
8
12
8


In [121]:
a

array([[[41, 49, 33, 29],
        [17, 16, 18,  3],
        [30, 36, 43, 18]],

       [[20, 29, 15, 34],
        [23, 37, 38,  8],
        [35, 12,  9,  8]]])

In [125]:
#b. when even 2d array even rows even cols -- replace them with 0 otherwise -1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
             if i%2==0 and j%2==0 and k%2==0:
                 a[i,j,k] = 0
             else:
                 a[i,j,k] = -1

In [127]:
a

array([[[ 0, -1,  0, -1],
        [-1, -1, -1, -1],
        [ 0, -1,  0, -1]],

       [[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]]])

In [131]:
#c. when elements are even replace them with 0 otherwise -1 ---- using np.nditer #o(n)
a= np.random.randint(1,50,(2,3,4))
a

array([[[46, 41,  7, 21],
        [21,  5,  8, 34],
        [23,  5, 44, 12]],

       [[ 8, 38, 25, 10],
        [21,  5,  3, 10],
        [ 2, 12, 17, 24]]])

In [141]:
for i in np.nditer(a,op_flags=['readwrite']):
    if i%2==0:
        i[...] = 0
    else:
        i[...] =-1

print(a)

[[[ 0 -1 -1 -1]
  [-1 -1  0  0]
  [-1 -1  0  0]]

 [[ 0  0 -1  0]
  [-1 -1 -1  0]
  [ 0  0 -1  0]]]


In [153]:
#d. boolean indexing
a= np.random.randint(1,50,(2,3,4))
a

array([[[47, 32, 21, 33],
        [46, 14, 41, 29],
        [45, 25, 47, 13]],

       [[ 3, 34, 22, 41],
        [44, 47,  5, 36],
        [45, 14, 22,  6]]])

In [147]:

a[a%2 == 0] =0
a

array([[[33, 47,  0,  0],
        [ 0, 49, 33,  0],
        [ 0, 37,  0,  0]],

       [[ 7,  0,  0,  0],
        [35, 29,  3, 21],
        [ 0,  0,  0, 41]]])

In [149]:
a

array([[[33, 47,  0,  0],
        [ 0, 49, 33,  0],
        [ 0, 37,  0,  0]],

       [[ 7,  0,  0,  0],
        [35, 29,  3, 21],
        [ 0,  0,  0, 41]]])

In [155]:
#e.by using where function

a= np.random.randint(1,50,(2,3,4))
a

array([[[30, 35, 23, 46],
        [44, 23,  7, 36],
        [27, 22, 19, 35]],

       [[ 2, 33, 19, 31],
        [44,  8,  8, 20],
        [ 3, 27, 13,  8]]])

In [157]:
np.where(a%2==0,0,-1)

array([[[ 0, -1, -1,  0],
        [ 0, -1, -1,  0],
        [-1,  0, -1, -1]],

       [[ 0, -1, -1, -1],
        [ 0,  0,  0,  0],
        [-1, -1, -1,  0]]])

In [159]:
a

array([[[30, 35, 23, 46],
        [44, 23,  7, 36],
        [27, 22, 19, 35]],

       [[ 2, 33, 19, 31],
        [44,  8,  8, 20],
        [ 3, 27, 13,  8]]])

In [36]:
np.min(a,axis=0) #elements

array([[5, 2, 2, 1, 5],
       [2, 5, 1, 1, 4],
       [1, 4, 2, 2, 1],
       [3, 3, 1, 2, 7]])

In [38]:
np.min(a,axis=1) #col wise

array([[1, 3, 3, 1, 1],
       [4, 2, 1, 1, 5],
       [2, 4, 1, 1, 3]])

In [128]:
np.min(a,axis=2) #row wise

array([[1, 2, 2, 2],
       [2, 1, 2, 1],
       [1, 1, 3, 2]])

In [161]:
k= np.array([[1,2,3],[4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
f(k)

array([[   1,   32,  243],
       [1024, 3125, 7776]], dtype=int32)

In [183]:
def f(x):
    return min(x)
    
f([1,2,3,4])
f(2)

TypeError: 'int' object is not iterable

In [169]:
k

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
np.apply_along_axis(f, 0, k)

array([[   1,   32,  243],
       [1024, 3125, 7776]], dtype=int32)

In [175]:
np.apply_along_axis(f, 1, k)

array([[   1,   32,  243],
       [1024, 3125, 7776]], dtype=int32)

In [177]:
k= np.array([[1,2,3],[4,5,10],[2,1,2]])
k

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 2,  1,  2]])

In [64]:
np.apply_along_axis(lambda x: min(x), 0, k)

array([1, 1, 2])

In [62]:
np.apply_along_axis(lambda x: min(x), 1, k)

array([1, 4, 1])

# task

1. explore Copy vs View

2. Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all numbers which are divisible by 5 with python and which are not divsible by 5 replace them with java.**

1. using two for loops
2. using one loop(nditer)
3. without using loop 
a.(boolean indexing)
b.(where)

3. write a function to return prime numbers.
a. create a random numpy array of shape(5,4) with integers in it and from that random array 
  get the prime numbers using the above created function.
b. apply the function along different axis'es

In [ ]:
https://numpy.org/doc/stable/reference/