In [1]:
# creating a dataframe from a list

# creating a dataframe from a tuple

# creating a dataframe from a dictionary

# attributes and methods of a dataframe
# attributes - shape,columns,index
# methods - head,describe,info

In [2]:
# reading a csv file
# reading a xlsx file

# basic operations - head,tail, info,columns


# - sum()
# - min() and max()
# - mean(), median(), var() and std()
# - describe()
# - corr(), skew() and kurt()
# - count(), unique(), nunique() and value_counts()
# - DataFrame.agg()

In [3]:
# 1. Filter a single column
# 2. Filter multiple columns

In [4]:
# creating a dataframe from a list

# creating a dataframe from a tuple

# creating a dataframe from a dictionary

# attributes and methods of a dataframe
# attributes - shape,columns,index
# methods - head,describe,info

# Dataframe - Dictionary

# numpy array - n dimensional arrays
# series - 1dimensional array - column

# group of series - dataframe or table

In [5]:
# how to create 1d array using numpy
import numpy as np
a = np.array([1,5,6,7,8])

In [22]:
import pandas as pd

b = pd.Series([1,5,6,7,8]) # 1 D 
b

0    1
1    5
2    6
3    7
4    8
dtype: int64

In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(type(b))

<class 'pandas.core.series.Series'>


In [9]:
# accessing - indexing - numberwise, slicing 

print(a[3])
print(b[3])

7
7


In [10]:
print(a[3:5])

[7 8]


In [11]:
print(b[3:5])

3    7
4    8
dtype: int64


In [12]:
# let us create dataframe from series

In [13]:
col1 = np.arange(40,61,2)
col2 = np.arange(80,100,2)

In [14]:
col1 = pd.Series(col1)
col2 = pd.Series(col2)

In [15]:
d = {"col1":col1,"col2":col2}

In [16]:
data = pd.DataFrame(d,columns=["col1","col2"],)

# data , columns
# len of the columns are not same then youll end up with missin values

# 1 D array 



In [17]:
data

col1  col2
0     40  80.0
1     42  82.0
2     44  84.0
3     46  86.0
4     48  88.0
5     50  90.0
6     52  92.0
7     54  94.0
8     56  96.0
9     58  98.0
10    60   NaN

In [18]:
# creating a dataframe from a list

# creating a dataframe from a tuple

data = [[45,65,"charan"],[95,65,"rakesh"]]

In [19]:
F = pd.DataFrame(data,columns=["M1","M2","Student_Name"])

In [20]:
F

M1  M2 Student_Name
0  45  65       charan
1  95  65       rakesh

In [21]:
# Excel file, CSV

# Database

# for loading a csv file

# pd.read_csv("path to file")

data = pd.read_csv(r"C:\Users\DELL E5490\OneDrive\Desktop\std_data1.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DELL E5490\\OneDrive\\Desktop\\std_data1.csv'

In [ ]:
data.columns

In [ ]:
data.SNAME[0:4]

In [ ]:
data["SCLASS "][0:4]

In [ ]:
# data.column[index] # oops -attribute,method
# data["colum_name"][index] - dictionaries

In [ ]:
# attributes and methods of a dataframe
# attributes - shape,columns,index
# methods - head,describe,info

In [ ]:
# attributes - shape, cols, index
print(data.shape)
print(data.columns)
print(data.index)

In [ ]:
# methods - head,describe,info

In [ ]:
data.head() # first 5 rows

In [ ]:
data.tail() # first 5 rows

In [ ]:
data.describe() # numerical cols 

In [ ]:
data.info()

In [ ]:
data

In [ ]:
# - sum()
# - min() and max()
# - mean(), median(), var() and std()
# - describe()
# - corr(), skew() and kurt()
# - count(), unique(), nunique() and value_counts()

In [ ]:
data["ENGLISH"].sum()

In [ ]:
data["ENGLISH"].min()

In [ ]:
data["ENGLISH"].max()

In [ ]:
data["ENGLISH"].mean()

In [ ]:
data["ENGLISH"].median()

In [ ]:
data["ENGLISH"].var()

In [ ]:
data["ENGLISH"].std()

In [ ]:
# - corr() -  relationship b
# - skew()
# - kurt()

In [ ]:
data["ENGLISH"].plot(kind="density")

In [ ]:
data["ENGLISH"].skew() # skewness measure - measure of symmetry 

In [ ]:
data["ENGLISH"].kurt() # 

In [ ]:
data[["ENGLISH","COMPUTER","SCIENCE"]].corr()

In [ ]:
# - count(), unique(), nunique() and value_counts()

In [ ]:
df = pd.read_csv(r"C:\Users\DELL E5490\OneDrive\Desktop\Backup_13-08-2024\data\loandata.csv")

In [ ]:
df.head()

In [ ]:
df["Married"].value_counts()

col1  col2 col3
0     40  80.0  NaN
1     42  82.0  NaN
2     44  84.0  NaN
3     46  86.0  NaN
4     48  88.0  NaN
5     50  90.0  NaN
6     52  92.0  NaN
7     54  94.0  NaN
8     56  96.0  NaN
9     58  98.0  NaN
10    60   NaN  NaN

In [26]:
F = pd.DataFrame(data,columns=["M1","M2","Student_Name"])

In [27]:
F

M1  M2  Student_Name
0  NaN NaN           NaN
1  NaN NaN           NaN
2  NaN NaN           NaN
3  NaN NaN           NaN
4  NaN NaN           NaN
5  NaN NaN           NaN
6  NaN NaN           NaN
7  NaN NaN           NaN
8  NaN NaN           NaN
9  NaN NaN           NaN
10 NaN NaN           NaN

In [29]:
house_array=np.random.randint(500,1700,30)
house_array

array([1506,  785,  634,  766, 1124,  718, 1000, 1249,  809, 1640,  895,
        844,  803, 1656,  812,  901, 1641, 1639, 1189,  892, 1386, 1589,
       1475,  816, 1018, 1602, 1607, 1670, 1676,  736])

In [75]:
rooms=np.random.randint(2,6,30)
rooms

array([3, 5, 4, 5, 5, 4, 4, 2, 3, 3, 4, 4, 2, 5, 4, 5, 5, 3, 2, 5, 3, 3,
       3, 3, 3, 4, 4, 3, 5, 3])

In [76]:
brooms=np.random.randint(1,4,30)
brooms

array([1, 3, 2, 2, 2, 2, 3, 3, 1, 3, 3, 1, 2, 1, 2, 2, 1, 2, 3, 2, 2, 2,
       3, 3, 2, 3, 3, 1, 2, 2])

In [77]:
import pandas as pd
data={"housearea":house_array,"no_ofrooms":rooms,"no_ofbroooms":brooms}
data

{'housearea': array([1506,  785,  634,  766, 1124,  718, 1000, 1249,  809, 1640,  895,
         844,  803, 1656,  812,  901, 1641, 1639, 1189,  892, 1386, 1589,
        1475,  816, 1018, 1602, 1607, 1670, 1676,  736]),
 'no_ofrooms': array([3, 5, 4, 5, 5, 4, 4, 2, 3, 3, 4, 4, 2, 5, 4, 5, 5, 3, 2, 5, 3, 3,
        3, 3, 3, 4, 4, 3, 5, 3]),
 'no_ofbroooms': array([1, 3, 2, 2, 2, 2, 3, 3, 1, 3, 3, 1, 2, 1, 2, 2, 1, 2, 3, 2, 2, 2,
        3, 3, 2, 3, 3, 1, 2, 2])}

In [78]:
df=pd.DataFrame(data)
df

housearea  no_ofrooms  no_ofbroooms
0        1506           3             1
1         785           5             3
2         634           4             2
3         766           5             2
4        1124           5             2
5         718           4             2
6        1000           4             3
7        1249           2             3
8         809           3             1
9        1640           3             3
10        895           4             3
11        844           4             1
12        803           2             2
13       1656           5             1
14        812           4             2
15        901           5             2
16       1641           5             1
17       1639           3             2
18       1189           2             3
19        892           5             2
20       1386           3             2
21       1589           3             2
22       1475           3             3
23        816           3             3
24       1018           3             2
25       1602           4             3
26       1607           4             3
27       1670           3             1
28       1676           5             2
29        736           3             2

In [67]:
df=df.columns.str.lower()
df

Index(['housearea', 'no_ofrooms', 'no_ofbroooms'], dtype='object')

In [88]:
df["housearea"]=df["housearea"].astype(float)
df["housearea"]

0     1506.0
1      785.0
2      634.0
3      766.0
4     1124.0
5      718.0
6     1000.0
7     1249.0
8      809.0
9     1640.0
10     895.0
11     844.0
12     803.0
13    1656.0
14     812.0
15     901.0
16    1641.0
17    1639.0
18    1189.0
19     892.0
20    1386.0
21    1589.0
22    1475.0
23     816.0
24    1018.0
25    1602.0
26    1607.0
27    1670.0
28    1676.0
29     736.0
Name: housearea, dtype: float64

In [85]:
df["no_ofrooms"]=df["no_ofrooms"].astype(int)
df["no_ofrooms"]

0     3
1     5
2     4
3     5
4     5
5     4
6     4
7     2
8     3
9     3
10    4
11    4
12    2
13    5
14    4
15    5
16    5
17    3
18    2
19    5
20    3
21    3
22    3
23    3
24    3
25    4
26    4
27    3
28    5
29    3
Name: no_ofrooms, dtype: int32

In [90]:
df[(df["housearea"]) > 500 & df(["housearea"] > 800 )]

TypeError: '>' not supported between instances of 'list' and 'int'