#### 11/09/2023

In [1]:
!pip install numpy

#when you are installing a library 

In [2]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
# 3 Dimentional array acess 2nd row 3 element

In [4]:
a = np.array([1,2,3],ndmin = 3)
print(a.shape)
print(a)

(1, 1, 3)
[[[1 2 3]]]


In [5]:
a

array([[[1, 2, 3]]])

In [6]:
a = np.array([[[1,2,3],[34,45,56],[54,55,67]]])
print(a.shape)
print(a)

(1, 3, 3)
[[[ 1  2  3]
  [34 45 56]
  [54 55 67]]]


In [7]:
# 1D array

In [8]:
y = [1,2,3,4]
for i in range(1,len(y)):
     y[i] = i*4
print(y)

[1, 4, 8, 12]


In [9]:
y=np.array([1,2,3,4])
y=y*4
print(y)

[ 4  8 12 16]


In [10]:
#boolean indexing
#to filter out
#consider subsets

In [11]:
a = np.arange(20,40,2)
print(a)

[20 22 24 26 28 30 32 34 36 38]


In [12]:
import random 
random.randint(10,20)

19

In [13]:
my_table = np.random.randint(10,40,size = (10,10))
print(my_table)

[[17 38 28 34 13 21 27 11 34 23]
 [27 35 12 24 15 12 29 32 32 32]
 [37 13 34 13 15 23 18 25 12 21]
 [36 36 29 33 27 26 10 28 16 36]
 [15 37 34 22 17 23 13 25 25 11]
 [25 38 39 38 22 22 25 24 18 22]
 [25 24 38 11 17 22 16 29 29 16]
 [35 22 19 38 34 29 25 26 28 15]
 [18 31 37 31 35 16 18 13 13 15]
 [36 26 34 17 11 34 37 24 16 38]]


In [14]:
my_table[7:10,7:10]#last 3 rows 3 columns

array([[26, 28, 15],
       [13, 13, 15],
       [24, 16, 38]])

In [15]:
my_table[0:10,3]#ftsr column acessed

array([34, 24, 13, 33, 22, 38, 11, 38, 31, 17])

In [16]:
my_table[:,3]

array([34, 24, 13, 33, 22, 38, 11, 38, 31, 17])

In [17]:
# Lets create a 2dimentional array with integers


table1 = np.random.randint(10,20,size = (10,8))
print(table1)
print(table1.shape) 

[[12 10 10 14 17 14 12 10]
 [10 10 13 16 15 11 14 18]
 [19 19 18 18 14 10 15 14]
 [11 10 15 19 19 18 16 16]
 [17 10 13 11 15 10 16 14]
 [15 12 16 16 19 18 19 18]
 [15 17 15 14 13 11 16 11]
 [12 18 13 13 17 11 15 15]
 [18 18 16 12 14 10 13 17]
 [18 14 16 11 18 12 16 16]]
(10, 8)


In [18]:
print(np.ndarray.flatten(table1))

[12 10 10 14 17 14 12 10 10 10 13 16 15 11 14 18 19 19 18 18 14 10 15 14
 11 10 15 19 19 18 16 16 17 10 13 11 15 10 16 14 15 12 16 16 19 18 19 18
 15 17 15 14 13 11 16 11 12 18 13 13 17 11 15 15 18 18 16 12 14 10 13 17
 18 14 16 11 18 12 16 16]


In [19]:
table2 =  np.random.randint(1,10,size = (10,8))
print(table2)
print(np.ndarray.flatten(table2))

[[4 8 4 1 6 6 6 7]
 [4 7 5 7 9 1 9 9]
 [1 8 2 7 8 8 6 5]
 [7 8 2 9 6 1 3 9]
 [6 7 4 3 7 1 7 3]
 [5 7 6 7 2 7 8 9]
 [7 5 2 8 8 2 3 9]
 [6 7 3 6 3 7 9 9]
 [1 1 8 1 9 2 3 4]
 [8 1 1 1 3 9 4 3]]
[4 8 4 1 6 6 6 7 4 7 5 7 9 1 9 9 1 8 2 7 8 8 6 5 7 8 2 9 6 1 3 9 6 7 4 3 7
 1 7 3 5 7 6 7 2 7 8 9 7 5 2 8 8 2 3 9 6 7 3 6 3 7 9 9 1 1 8 1 9 2 3 4 8 1
 1 1 3 9 4 3]


In [20]:
 table2 =  np.random.randint(1,27,size = (3,3,3))
print(table2)
print(np.ndarray.flatten(table2))

[[[ 6  5 20]
  [14  6 14]
  [15  1  3]]

 [[ 1 13 21]
  [ 4 10  6]
  [ 6 18 14]]

 [[ 2 21 26]
  [26  1 12]
  [20 18 11]]]
[ 6  5 20 14  6 14 15  1  3  1 13 21  4 10  6  6 18 14  2 21 26 26  1 12
 20 18 11]


In [21]:
import numpy as np

A = np.array([7,8,32,45,64,92],dtype = "int64")

np.std(A)
np.var(A)

911.888888888889

In [22]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6])
c=np.array([93,48,102,111])
print(a)
print(b)
print(c)
np.corrcoef([a,c])

[1 2 3 4 5]
[3 4 5 6]
[ 93  48 102 111]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
np.corrcoef([a,b])

In [ ]:
np.corrcoef([a,c])

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
a.shape

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


(1, 3, 3)

In [ ]:
# Accessing the element in the 2nd row, 3rd column of the first (and only) layer
# Note: Indexing starts at 0, so 2nd row is index 1 and 3rd element is index 2
a[0, 1, 2] = "text"

print(a)


In [ ]:
y=[1,2,3,4]
for i in range(0,len(y)):
    y[i] = y[i]*4
    print(y[i])

In [ ]:
z=np.array([1,2,3,4])
z = z*4
print(z)

In [ ]:
h=np.array([1,2,3,4,5,6,7,8,9,10])
print(h)
print(h.shape)
print(h.ndim)


In [1]:
!pip install numpy

#when you are installing a library 

In [2]:
!python --version

Python 3.11.5


In [3]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
arr=np.array([1,7,-6,8])
print(f" 1D ARRAY : {arr}")
print(type(arr))
print(arr.ndim)
print(arr.shape)
#it gives type of the whole array

 1D ARRAY : [ 1  7 -6  8]
<class 'numpy.ndarray'>
1
(4,)


In [ ]:
arr.dtype #it is giving individual data types in the array

In [ ]:
arr_2=np.array([ [1,2,3],
               [4,5,6] ])
print(f" 2D ARRAY :{arr_2}")
print(arr_2.shape)
print(type(arr_2))
print(arr_2.ndim)

In [ ]:
#to check dimensions we use arrayname.ndim

In [ ]:
#creating a simple 3D array
arr_3d=np.array([ [ [1,2,90],
                  [1,1,1]],
                 [[106,69,98],
                  [2,-3,8]] ])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)
#in shape 1st shows how  many nmatrices are taken
#2nd one rows and  consecutively it gives columns

In [ ]:
#to know the no of elements we use "arrayname.size"
print(arr_3d.size)

In [ ]:
# total the array contains memory as  "48bytes" 
#its syntax is "arrayname.nbytes" to know whole arrays memory
print(arr_3d.nbytes)

In [ ]:
#it shows how much memory an element contains "arrayname.itemsize"
arr_3d.itemsize

In [ ]:
arr1=np.array(([2,3,1],
               [5,6,7],
               [5,0,-1]))
print(arr1)
print(f"the array shape is : {arr1.shape} ")
print(f"the array dimension is : {arr1.ndim} dimensions")
print(f"the array size is : {arr1.size} elements")
print(f"the arrays memory size of an element : {arr1.itemsize} bytes")
print(f"the arrays whole memory  is : {arr1.nbytes} bytes")
arr1.dtype

In [ ]:
#default when we give zeros matrix iut takes "float"
zeros=np.zeros((2,3),dtype = np.int16)
print(f"array of zeroes:\n {zeros}")

zeros.dtype

In [ ]:
zeros.nbytes

In [ ]:
zeros.itemsize

In [ ]:
one_arr=np.ones((5,4),dtype=np.int64)
print(one_arr)
print(one_arr.itemsize)
print(one_arr.nbytes)

#### 12/9/2024

In [24]:
#Create an array with range of elements
range_arr=np.arange(1,10,2)   #similar to python range
print("Range array :",range_arr)

Range array : [1 3 5 7 9]


In [ ]:
#create an array with evenly spaced numbers over specified interval

In [25]:
line_sparr=np.linspace(0,1,5)
#(stop-start/step-1) formula to find linspace both start and stop are included
print("linespace array:",line_sparr)

linespace array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
line_sparr=np.linspace(0,10,11)
print("linespace array:",line_sparr)

In [ ]:
line_sparr=np.linspace(0,20,12)
"linespace array:",line_sparr
#if we use print we can see elements without commas here we see array
#if we dont use print we can see it clearly with commas

In [ ]:
len(line_sparr)

In [ ]:
#matrix multipliacation
a=np.array([ [1,2],
           [3,4] ])
b=np.array([ [1,2,-1],
           [5,0,1] ])
a.shape,b.shape

In [ ]:
#matrix multiplication of a and b
res=a @ b
res.shape,res

In [ ]:
res1=b @ a
res1.shape,res
#here the no of col in frst matrix is not equal to rows of second matrix

In [ ]:
#creating diagonal elements 
#A matrix which has values on diagonal and remaining all values are equal "0"

In [ ]:
diag_matrix=np.diag([2,5,1,-1])
diag_matrix

In [ ]:
#identity matrix is defined as A*A^-1== I

In [ ]:
identity_matrix=np.eye(2,dtype=int)
identity_matrix

In [ ]:
#How to calculate inverse in pytho
#from numpy.linalg,import inv

In [ ]:
from numpy.linalg import inv
a=np.array([ [1,2],
           [3,4] ])
a_inv = inv(a)
a @ a_inv

In [ ]:
inv(a)

In [ ]:
#full is used to fill each and evry element in matrix to one value
full_arr = np.full( (3,4), -3 )
full_arr

In [ ]:
string_arr=np.array(["bachi","munnulakshmi"])
print(string_arr.dtype)
string_arr

In [ ]:
string_arr.itemsize

In [ ]:
string_arr.nbytes

In [ ]:
#NP.RANDOM.RAND background behind this is uniform distribution [0,1]
#gives values between O and 1

In [ ]:
#if we take seed and runs we get same values how many times we run the code

In [ ]:
np.random.seed(20)
np.random.rand(10)

In [ ]:
#uniform dist each element has equal chance of occuring
#u=1/(b-a)

In [ ]:
#generating random integers
random_int=np.random.randint(0,11,size = 20)
random_int

In [ ]:
#indexing and slicing 
#indexing we specify the rows,columns
#1D array

In [ ]:
arr_1dd=np.array([10,20,30,106,69,78])
arr_1dd

In [ ]:
arr_1dd[2]=106

In [ ]:
arr_1dd

In [ ]:
#sling changing multiple positions with an element at a time

In [ ]:
arr_1dd[:]=106

In [ ]:
arr_1dd

In [ ]:
#acessing in 2D array

In [ ]:
arr_2=np.array([ [1,2,3],
               [4,5,6] ])
arr_2

In [ ]:
#in 2D array acess rows frst and then columns element can be acessed
arr_2[1,2]=89 

In [ ]:
arr_2

In [ ]:
_2d=np.array([[1,2,3,11],
            [4,5,6,15],
            [7,8,9,-1]])
_2d

In [ ]:
#Acessing the element at 2nd row(index1) and 3rd column (index 2)
_2d[1,2]

In [ ]:
#Acessing the element at last row and last column
_2d[2,3] #here last row index is 2 and last column index is 3

In [ ]:
#Acessing the element at first row and last column
_2d[0,3] #here first row index is 0 and last column index is 3

In [ ]:
#Acessing the element in middle row and last column
_2d[1,3] #here first row index is 0 and last column index is 3

#### 13/9/2024

In [30]:
(56+66+75+72+81+100)/6

75.0

In [31]:
147/2

73.5

In [34]:
#considering all weights and calculating mean
weights=np.array([56,66,72,75,81,100,110,120])
np.mean(weights),np.median(weights)

(85.0, 78.0)

In [35]:
diff=np.mean(weights)-np.median(weights)
diff

7.0

In [37]:
#removing outliers and calculating mean and median u can see less diff
#mean is effected due to outliers
#median is calculated as arrange them in ascending order
#then middle observation is median
weights=np.array([56,66,72,75,81])
np.mean(weights),np.median(weights)

(70.0, 72.0)

In [40]:
np.max(weights)

81

In [41]:
np.min(weights)

56

In [43]:
#range is defined as differnce of maximum value and minimum value
range_1=np.max(weights)-np.min(weights)
range_1

25

In [44]:
weights=np.array([56,66,72,75,81])
weights

array([56, 66, 72, 75, 81])

In [48]:
sum(weights)/len(weights)

70.0

In [50]:
xi_mu=weights-(70)
xi_mu

array([-14,  -4,   2,   5,  11])

In [52]:
square=xi_mu**2
square

array([196,  16,   4,  25, 121])

In [54]:
var=sum(square)/len(square)
var

72.4

In [59]:
np.std(weights)

72.39999999999999

In [69]:
distances=np.array([15,20,25,30,12,14,15,21,22])
print(f" mean is : {np.mean(distances)}")
print(f" median is : {np.median(distances)}")
print(f" range is {max(distances)-min(distances)}")
print(f" variance is : {np.var(distances)}")
print(f" standarddeviation is : {np.std(distances)}")

 mean is : 19.333333333333332
 median is : 20.0
 range is 18 
 variance is : 30.66666666666667
 standarddeviation is : 5.5377492419453835


In [ ]:
#25percent quartile(Q1) it is calculated as median of frst half of the data
#75percent quartile(Q3) it is calculated as median of second half of the data
#

In [85]:
marks=np.array([78,66,64,89,91,75,62,65,86,92,79])
marks
sorting=(np.sort(marks))
print(sorting)

[62 64 65 66 75 78 79 86 89 91 92]


In [86]:
_25=sorting[0:5]
_25

array([62, 64, 65, 66, 75])

In [87]:
_75=sorting[6:]
_75

array([79, 86, 89, 91, 92])

In [92]:
import pandas as pd
intrest=pd.DataFrame(["1","1","1","2","2"])
intrest

0
0  1
1  1
2  1
3  2
4  2

#### 17/09/2024

In [8]:
#Creating a 1D array
#indexing and slicing in numpy array
arrray_1=np.array([10,20,30,40,50])
arrray_1[3],arrray_1[2:7]

(40, array([30, 40, 50]))

In [ ]:
#in indexing when we give out of range it throws an error
#but inslicing when we give out of range also it doesnt give any error.

In [16]:
#Creating a 2D array
array_2=np.array([[1,2,3],[45,56,78],[789,890,901]])
print(array_2)
array_2[1:,1:]

[[  1   2   3]
 [ 45  56  78]
 [789 890 901]]


array([[ 56,  78],
       [890, 901]])

In [19]:
# To obtain first row
array_2[0]

array([1, 2, 3])

In [25]:
# To acess last column
array_2[:,-1]

array([  3,  78, 901])

In [34]:
array_3=np.array([[ [5,1],[0,2]],[[0,-1],[1,2]]])
array_3

array([[[ 5,  1],
        [ 0,  2]],

       [[ 0, -1],
        [ 1,  2]]])

In [35]:
array_3[1,0,1] #1st matrix,0th row,1st element

-1

In [41]:
array_3[0,1,1]

2

In [42]:
array_3.shape

(2, 2, 2)

In [46]:
#acess last matrix
array_3[1]

array([[ 0, -1],
       [ 1,  2]])

In [63]:
array_3=np.array([[ [5,1],[0,2]],[[0,-1],[1,2]]])
array_3

array([[[ 5,  1],
        [ 0,  2]],

       [[ 0, -1],
        [ 1,  2]]])

In [55]:
#Acess element at first matrix at row index 0 and last column
print(array_3[0,0,-1]) #0th matrix

1


In [57]:
#Acess first matrix and last row
array_3[0,-1] 

array([0, 2])

In [58]:
# Acess first matrix and left most column of last row
array_3[0,-1,0]

0

In [76]:
array_2=np.array([[1,2,3],[45,56,78],[789,890,901]])
#acessing 3rd row i.e 2nd index and 2nd column i.e 1st index
array_2[2,1]=-20
array_2

array([[  1,   2,   3],
       [ 45,  56,  78],
       [789, -20, 901]])

In [77]:
#acessing each and every row and 1st column i.e is 0th index
array_2[:,0]=200
array_2

array([[200,   2,   3],
       [200,  56,  78],
       [200, -20, 901]])

In [78]:
#acessing submatrix and updating sub matrix
#1st "1:" takes from index 1 row to last row and 2nd  "1:" takes from  index 1 column to last index column
array_2[1:,1:]=np.array([[-5,-4],[-3,-2]])
array_2

array([[200,   2,   3],
       [200,  -5,  -4],
       [200,  -3,  -2]])

In [79]:
# array_2[0]=-10
# array_2
array_2[0]=np.array([[-10,-10,-10]])
array_2

array([[-10, -10, -10],
       [200,  -5,  -4],
       [200,  -3,  -2]])

In [80]:
#boolean indexing
array_2>0

array([[False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [81]:
#when ever the values > 0 it returns only "True" values
#advanced slicing
array_2[array_2>0]

array([200, 200])

In [82]:
array_2[array_2>-4]

array([200, 200,  -3,  -2])

In [83]:
arrray_1=np.array([10,20,30,40,50])
arrray_1

array([10, 20, 30, 40, 50])

In [84]:
#Reversing the array
arrray_1[::-1]

array([50, 40, 30, 20, 10])

In [85]:
arrray_1[::2]

array([10, 30, 50])

In [88]:
runs_km=np.array([5,4,5,1,2])
calories_burnt=np.array([100,90,120,50,70])
np.corrcoef(runs_km,calories_burnt)

array([[1.        , 0.95758968],
       [0.95758968, 1.        ]])

In [89]:
np.cov(runs_km,calories_burnt)

array([[  3.3,  47. ],
       [ 47. , 730. ]])

In [31]:
# array_22=np.arange(1,19).reshape(3,2,3)
# array_22

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [90]:
runs_km=np.array([15,14,14,14,13])
calories_burnt=np.array([100,101,99,98,100])
np.corrcoef(runs_km,calories_burnt)
# Zero correlation

array([[1., 0.],
       [0., 1.]])

In [6]:
arr_2=np.array([ [1,2,3],
               [4000,5000000,690] ])
for i  in np.nditer(arr_2):
    print(i)

1
2
3
4000
5000000
690


In [7]:
with np.nditer(arr_2,op_flags = ["readonly"]) as it:
    for x in it:
        print(x)
        x[...] = x * 2
print(arr_2)

1


ValueError: assignment destination is read-only

In [8]:
with np.nditer(arr_2,op_flags = ["readonly"]) as it:
    for x in it:
        print(x)
#         x[...] = x * 2
print(arr_2)

1
2
3
4000
5000000
690
[[      1       2       3]
 [   4000 5000000     690]]


In [9]:
for x in np.nditer(arr_2,flags=["external_loop"],order = "c"):
    print(x)

[      1       2       3    4000 5000000     690]


In [10]:
for x in np.nditer(arr_2,flags=["external_loop"],order = "f"):
    print(x)

[   1 4000]
[      2 5000000]
[  3 690]


In [12]:
corder_output=[]
for x in np.nditer(arr_2,flags=["external_loop"],order = "c"):
    print(id(x))
    corder_output.append(x)
    print(x)
corder_output

2563159291152
[      1       2       3    4000 5000000     690]


[array([      1,       2,       3,    4000, 5000000,     690])]

In [13]:
corder_output=[]
for x in np.nditer(arr_2,flags=["external_loop"],order = "f"):
    print(id(x))
    corder_output.append(x)
    print(x)
corder_output

2563159291920
[   1 4000]
2563153338096
[      2 5000000]
2563153338384
[  3 690]


[array([   1, 4000]), array([      2, 5000000]), array([  3, 690])]

In [15]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])


import numpy as np

#create two arrays of same size element wise addition
addition = a + b
print("addition:\n", addition)

#element wise subtraction
subtraction = a - b
print("subtraction:\n",subtraction)

#eelement wise multiplication
multiplication = a * b
print("multiplication:\n",multiplication)

#element wise division
division = a / b
print('division:\n',division)


addition:
 [11 22 33 44]
subtraction:
 [ -9 -18 -27 -36]
multiplication:
 [ 10  40  90 160]
division:
 [0.1 0.1 0.1 0.1]


In [16]:
a=np.arange(1,21).reshape(4,5)
b=np.arange(21,41).reshape(4,5)

addition = a + b
print("addition:\n", addition)

#element wise subtraction
subtraction = a - b
print("subtraction:\n",subtraction)

#eelement wise multiplication
multiplication = a * b
print("multiplication:\n",multiplication)

#element wise division
division = a / b
print('division:\n',division)


addition:
 [[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
subtraction:
 [[-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]]
multiplication:
 [[ 21  44  69  96 125]
 [156 189 224 261 300]
 [341 384 429 476 525]
 [576 629 684 741 800]]
division:
 [[0.04761905 0.09090909 0.13043478 0.16666667 0.2       ]
 [0.23076923 0.25925926 0.28571429 0.31034483 0.33333333]
 [0.35483871 0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949 0.5       ]]


In [2]:
import numpy as np
d=np.arange(2,10).reshape(2,4)
e=np.arange(12,20).reshape(4,2)

#dot product
dot=np.dot(d,e)
print("dotproduct:\n",dot)


#matrix multiplication using @ operator
matrixproduct= d @ e
print("matrixproduct:\n",matrixproduct)

#sum of all elements
total_sum=np.sum(d)
print("totalsum:\n",total_sum)

#sum along the first axis (sum of each column)
column_sum=np.sum(d,axis=0)
print("sum along the columns:\n",column_sum)

row_sum = np.sum(d,axis=1)
print('sum along the rows:/n',row_sum)



dotproduct:
 [[220 234]
 [460 490]]
matrixproduct:
 [[220 234]
 [460 490]]
totalsum:
 44
sum along the columns:
 [ 8 10 12 14]
sum along the rows:/n [14 30]


In [34]:
#corr_matrix

d=np.arange(2,10).reshape(2,4)
e=np.arange(1,9).reshape(2,4)


corr_matrix= np.corrcoef(d,e)
print("correlation matrix between x and y:\n",corr_matrix)

correlation matrix between x and y:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.random.randint()

In [35]:
f=np.array([12,13,14])
g=np.array([34,45,67])
concatenate=np.concatenate((f,g),axis = 0)
concatenate

array([12, 13, 14, 34, 45, 67])

In [39]:
f=np.array([12,13,14])
g=np.array([34,45,67])
f=f.reshape(3,-1)
g=g.reshape(3,-1)
concatenate=np.concatenate((f,g),axis = 1)
concatenate

array([[12, 34],
       [13, 45],
       [14, 67]])

In [45]:
a=[1,2,1,2,1,1,1,1,3,3,4,5,5,5,5,5,5,5,5,5,5,5,5]
b={}
for i in a:
    if i in b:
        b[i]=b[i]+1
    else:
        b[i] = 1
print(b)
    

{1: 6, 2: 2, 3: 2, 4: 1, 5: 12}


In [42]:
f=np.array([12,13,14])
g=np.array([34,45,67])
f=f.reshape(-1,3)
g=g.reshape(-1,3)
out_array=np.empty((1,6),dtype = "int")
np.concatenate((f,g),axis = 1,out=out_array)
out_array.reshape(2,-1),out_array.shape

(array([[12, 13, 14],
        [34, 45, 67]]),
 (1, 6))

In [44]:
f=np.array([12,13,14])
g=np.array([34,45,67])
columnstack=np.column_stack((f,g))
print("column stack:\n",columnstack)

column stack:
 [[12 34]
 [13 45]
 [14 67]]


In [47]:
nmf=np.array([12,78,97326871,72192,7183098103,14])
np.sort(f,axis=0)

array([        12,         14,         78,      72192,   97326871,
       7183098103], dtype=int64)

# 20/9/2024