###### Q1. Create a 2x3 NumPy array with random integers. Multiply each column by a different scalar value without using a loop.


In [47]:
import numpy as np
# Creating a (2x3) numpy array using random numbers 
array = np.random.randint(25,32,(2,3))
scalar_val = [1,2,3]
print("The created array is ",array)
print("\nArray is multiplied by each col with different value",scalar_val,)
print("\nThe modified array is ",array * scalar_val)

The created array is  [[30 26 27]
 [28 27 30]]

Array is multiplied by each col with different value [1, 2, 3]

The modified array is  [[30 52 81]
 [28 54 90]]


In [53]:
# Multiplying each value with scalar 2
array = np.random.randint(25,32,(2,3))
scalar_val = 2
print(array)
print(f"\nafter multiplying {scalar_val} to every element in array ",array * scalar_val )

[[28 30 30]
 [25 27 25]]

after multiplying 2 to every element in array  [[56 60 60]
 [50 54 50]]


###### Create a NumPy array with shape (3, 3) filled with random values. Add a scalar value to each element in the array using broadcasting.


In [56]:
array1 = np.random.randint(60,70,(3,3))
print(array1)
scalar_value = 106
# adding a scalar using broad casting
print(f"After adding {scalar_value} to each and every element in array ,{array1 + scalar_value} ")

[[60 64 62]
 [68 67 68]
 [67 60 68]]
After adding 106 to each and every element in array ,[[166 170 168]
 [174 173 174]
 [173 166 174]] 


###### Q2. Create two NumPy arrays with unique integer values. Find the intersection of the two sets using NumPy


In [21]:
array2 = np.random.randint(100,110,(2,5))
array3 = np.random.randint(100,110,(2,5))
print(array2)
print()
print(array3)

[[108 106 105 101 108]
 [105 106 109 105 101]]

[[101 108 101 100 108]
 [103 105 101 101 104]]


In [58]:
# for intersection of two arrays we use "intersect1d"
print("Intersection of two arrays",np.intersect1d(array2,array3))
print("\nIntersection of two arrays",np.intersect1d(array3,array2))

Intersection of two arrays [100 101 102 103 106]

Intersection of two arrays [100 101 102 103 106]


###### Generate two NumPy arrays with integers. Calculate the set difference between the two arrays.



In [26]:
array2 = np.random.randint(100,110,(2,5))
array3 = np.random.randint(100,110,(2,5))
print(array2)
print()
print(array3)

[[101 103 106 102 107]
 [104 108 102 106 100]]

[[106 103 102 105 109]
 [103 100 106 105 101]]


In [59]:
# for set difference of two sets we use "setdiff1d"
print("Set difference of two arrays",np.setdiff1d(array2,array3))
print("\nSet difference of two arrays",np.setdiff1d(array3,array2))

Set difference of two arrays [104 107 108]

Set difference of two arrays [105 109]


#### You are given two sets of data representing information about students:
#### Student Details:student_ids: An array of student IDs (integer values).
#### student_names: An array of student names (strings).
##### Exam Scores:
###### student_ids: An array of student IDs (integer values).
###### scores: An array of exam scores corresponding to the student IDs.
##### Your task is to perform the following operations using NumPy:


In [75]:
Student_id = np.array([34,35,36,37,38])
Student_names = np.array(["hari","varshi","munnu","ayush","bachi"])
marks = np.array([99,98,97,96,95])
print(Student_id)
print(Student_names)
print(marks)

[34 35 36 37 38]
['hari' 'varshi' 'munnu' 'ayush' 'bachi']
[99 98 97 96 95]


In [86]:
# Horizontally stacking the arrays
hor_stack=np.hstack((Student_id,Student_names))
hor_stack

array(['34', '35', '36', '37', '38', 'hari', 'varshi', 'munnu', 'ayush',
       'bachi'], dtype='<U11')

In [87]:
# Vertical stacking the arrays
verti_stack = np.vstack((Student_id,marks))
verti_stack

array([[34, 35, 36, 37, 38],
       [99, 98, 97, 96, 95]])

#### Merging:
#### Merge the student_info array with the exam_data array based on the common column (student_ids).
##### The result should be a 2D array named final_data with columns: student_ids, student_names, scores.


In [85]:
# Use column stack 
result = np.column_stack((Student_id,Student_names,marks))
result

array([['34', 'hari', '99'],
       ['35', 'varshi', '98'],
       ['36', 'munnu', '97'],
       ['37', 'ayush', '96'],
       ['38', 'bachi', '95']], dtype='<U11')

#### Appending: Append a new student's information to the final_data. The new student has an ID of 101, a name of 'New Student', and a score of 95.


In [96]:
a= np.array(["51","thanvika","95"])
appending = np.append(result,[a],axis=0)
print(appending)

[['34' 'hari' '99']
 ['35' 'varshi' '98']
 ['36' 'munnu' '97']
 ['37' 'ayush' '96']
 ['38' 'bachi' '95']
 ['51' 'thanvika' '95']]


#### Filtering: Filter and display only the rows from final_data where the student ID is in the range [50, 80].

