#### 1.A a. Create a 1D array using arange().
   - Use the flip() function to reverse the order of elements in a 1D array.
   - Achieve the same above output without using flip().


In [1]:
!pip install numpy
import numpy as np

In [2]:
arr_1d = np.array([2,1,3,45,56,69,78,106])
arr_1d

array([  2,   1,   3,  45,  56,  69,  78, 106])

In [3]:
#reversing the 1D array
np.flip(arr_1d)

array([106,  78,  69,  56,  45,   3,   1,   2])

In [4]:
arr_1d[-1:-9:-1]

array([106,  78,  69,  56,  45,   3,   1,   2])

In [5]:
arr_1d[::-1]

array([106,  78,  69,  56,  45,   3,   1,   2])

In [6]:
## B.Create a boolean array indicating which elements of the above 1D array are greater than 3.
## Replace all even numbers in the array with -1.

In [7]:
arr_1d[arr_1d > 3] #its not giving for values less than "3"

array([ 45,  56,  69,  78, 106])

In [8]:
arr_1d[arr_1d % 2 == 0]=-1
arr_1d

array([-1,  1,  3, 45, -1, 69, -1, -1])

## Q2. 
a. Generate a 2D array with random elements. 
   - Transpose the array.
   - Flatten the array 


In [9]:
np.random.seed(20)
arr_2d=np.random.randint(1,10,(3,3))
arr_2d

array([[4, 5, 7],
       [8, 3, 1],
       [7, 9, 6]])

In [10]:
np.transpose(arr_2d)

array([[4, 8, 7],
       [5, 3, 9],
       [7, 1, 6]])

In [11]:
#flatten converts anytype of array into 1D array in 1line
flat=arr_2d.flatten()
flat

array([4, 5, 7, 8, 3, 1, 7, 9, 6])

## b. 
- Include a value of 99 at index 2 in the above array.
- Add a value of 100 to the end of a given array.
- Delete the element at index 3 from the array.


In [12]:
#including "99" at index 2
flat[2]=99
flat

array([ 4,  5, 99,  8,  3,  1,  7,  9,  6])

In [17]:
#appending a element we have to give variablename and value
print("appending an element",np.append(flat,100))

appending an element [  4   5  99   8   3   1   7   9   6 100]


In [16]:
#Delete the element at index 3 from the array.
print("deleting the element at index 3",np.delete(arr_2d,2))

deleting the element at index 3 [4 5 8 3 1 7 9 6]


In [ ]:
# # Q3. 
# a. Create a 2D array. Iterate through the elements of the array and print elements using both nditer() and for loop.


In [19]:
array_2d = np.array([[1,2,3,4],[34,45,56,67]])
array_2d

array([[ 1,  2,  3,  4],
       [34, 45, 56, 67]])

In [20]:
for i in array_2d:
    print(i)

[1 2 3 4]
[34 45 56 67]


In [23]:
for i in np.nditer(array_2d):
    print(i)

1
2
3
4
34
45
56
67


In [ ]:
#b. Generate two arrays with random float elements in it.
#  - perform all python operations (* + - / % //).


In [58]:
a=np.random.uniform(0,1,10)
a

array([0.51064106, 0.26362883, 0.31051155, 0.62685344, 0.55744981,
       0.31857956, 0.39484322, 0.25797459, 0.58224112, 0.16162871])

In [59]:
b=np.random.uniform(0,1,10)
b

array([0.59813382, 0.82582358, 0.15639172, 0.73430052, 0.40864343,
       0.7786879 , 0.80397057, 0.78607144, 0.59228702, 0.6644892 ])

In [60]:
print("addition of two randomly generated arrays",a + b)

addition of two randomly generated arrays [1.10877488 1.08945241 0.46690327 1.36115396 0.96609324 1.09726746
 1.19881379 1.04404603 1.17452814 0.82611791]


In [61]:
print("subtraction of two randomly generated arrays",a * b)

subtraction of two randomly generated arrays [0.30543169 0.2177109  0.04856143 0.4602988  0.2277982  0.24807405
 0.31744233 0.20278646 0.34485386 0.10740053]


In [63]:
print("subtraction of two randomly generated arrays",a - b)

subtraction of two randomly generated arrays [-0.08749276 -0.56219475  0.15411983 -0.10744708  0.14880638 -0.46010834
 -0.40912735 -0.52809686 -0.0100459  -0.50286049]


In [64]:
print("division of two randomly generated arrays",a / b)

division of two randomly generated arrays [0.85372376 0.31923141 1.9854731  0.85367424 1.36414724 0.40912355
 0.49111651 0.32818211 0.98303881 0.24323753]


In [65]:
print("floor division of two randomly generated arrays",a // b)

floor division of two randomly generated arrays [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]


In [66]:
print("modulus of two randomly generated arrays",a  % b)

modulus of two randomly generated arrays [0.51064106 0.26362883 0.15411983 0.62685344 0.14880638 0.31857956
 0.39484322 0.25797459 0.58224112 0.16162871]


In [ ]:
#  - Also apply all mathematical functions on the two arrays.

In [67]:
np.sqrt(a,b)

array([0.71459153, 0.51344798, 0.55723563, 0.79174076, 0.74662562,
       0.56442852, 0.62836552, 0.50791199, 0.76304726, 0.40203073])

In [68]:
np.cos(a,b)

array([0.87243138, 0.96545072, 0.95217739, 0.80987729, 0.84860698,
       0.94968128, 0.92305688, 0.96690869, 0.83523236, 0.98696649])

In [69]:
np.sin(a,b)

array([0.48873662, 0.26058572, 0.30554576, 0.58659934, 0.52902381,
       0.31321791, 0.38466348, 0.25512269, 0.54989717, 0.1609259 ])

In [70]:
np.sinh(a,b)

array([0.53312417, 0.26669317, 0.31552545, 0.66872079, 0.58677301,
       0.3239959 , 0.40518291, 0.26084553, 0.61570034, 0.16233336])

In [71]:
np.cosh(a,b)

array([1.13323492, 1.03495181, 1.04859731, 1.20299106, 1.15944063,
       1.05117712, 1.07896858, 1.0334604 , 1.17434531, 1.01309038])

In [73]:
np.tan(a,b)

array([0.56020065, 0.26991095, 0.32089164, 0.72430644, 0.62340262,
       0.32981371, 0.41672781, 0.26385396, 0.65837628, 0.16305103])

In [75]:
np.tanh(a,b)

array([0.47044453, 0.25768655, 0.3009024 , 0.55588176, 0.50608285,
       0.30822199, 0.375528  , 0.25240012, 0.52429242, 0.16023581])

In [ ]:
# Q4. 
# Create a random NumPy array. Generate mean, mode, median, variance and standard deviation of that array.
# Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays


In [84]:
arrayyy=np.array([12,23,34,45,56,67,78,89,10,10,10,10,10,11])
arrayyy

array([12, 23, 34, 45, 56, 67, 78, 89, 10, 10, 10, 10, 10, 11])

In [85]:
np.mean(arrayyy)

33.214285714285715

In [86]:
np.var(arrayyy)

761.4540816326531

In [87]:
np.std(arrayyy)

27.59445744407114

In [88]:
np.median(arrayyy)

17.5

In [90]:
from scipy import stats as st
st.mode(arrayyy)

ModeResult(mode=10, count=5)

# Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays



In [93]:
aray1=np.array([10,11,12,13,14])
aray2=np.array([20,22,23,34,56])
print(aray1,aray2)
print(len(aray1),len(aray2))

[10 11 12 13 14] [20 22 23 34 56]
5 5


In [94]:
np.corrcoef(aray1,aray2)

array([[1.        , 0.88543774],
       [0.88543774, 1.        ]])

In [ ]:
## Here correlation coefficient is 0.8854377