In [ ]:
# iteration over numpy array
# cpncatenate, vstack, hstack, column_stack,hsplit,vsplit
# Broadcasting
# Numpy where

In [48]:
import numpy as np

In [55]:
A = np.array([1,2,3,4,5])
B = np.array([[1,2,3,4],[5,6,7,8]])

In [63]:
for i in np.nditer(B,flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [64]:
for i,d in np.ndenumerate(B):
    print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [66]:
np.hsplit(B,(1,0))

[array([[1],
        [5]]),
 array([], shape=(2, 0), dtype=int32),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [72]:
r =  np.arange(1,10,2)

In [73]:
r

array([1, 3, 5, 7, 9])

In [75]:
for i in r:
    print(i)

1
3
5
7
9


In [76]:
for i in range(0,len(r)):
    print(r[i])

1
3
5
7
9


In [78]:
d = np.random.randint(1,5,size=(3,3))

In [80]:
d

array([[3, 4, 1],
       [3, 3, 1],
       [1, 3, 3]])

In [83]:
for i in np.nditer(d,order="F",flags=['external_loop']):
    print(i)

[3 3 1]
[4 3 3]
[1 1 3]


In [84]:
for i in np.nditer(d,order="C",flags=['external_loop']):
    print(i)

[3 4 1 3 3 1 1 3 3]


In [89]:
for i in np.nditer(d,op_flags=["readwrite"]):
    i[...] = i*i

In [90]:
d

array([[ 81, 256,   1],
       [ 81,  81,   1],
       [  1,  81,  81]])

In [91]:
# cpncatenate, vstack, hstack, column_stack,hsplit,vsplit

In [95]:
D = np.arange(10,20,1)

In [96]:
D

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [98]:
np.split(D,2)

[array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]

In [100]:
np.array_split(D,4)

[array([10, 11, 12]), array([13, 14, 15]), array([16, 17]), array([18, 19])]

In [108]:
F = np.random.randint(2,9,size=(4,4))

In [109]:
F

array([[4, 8, 7, 2],
       [8, 3, 7, 8],
       [6, 3, 6, 4],
       [4, 5, 4, 8]])

In [110]:
np.split(F,4)

[array([[4, 8, 7, 2]]),
 array([[8, 3, 7, 8]]),
 array([[6, 3, 6, 4]]),
 array([[4, 5, 4, 8]])]

In [121]:
np.hsplit(F,2)

[array([[4, 8],
        [8, 3],
        [6, 3],
        [4, 5]]),
 array([[7, 2],
        [7, 8],
        [6, 4],
        [4, 8]])]

In [122]:
np.hsplit(F,2)[0]

array([[4, 8],
       [8, 3],
       [6, 3],
       [4, 5]])

In [123]:
np.hsplit(F,[1,3])

[array([[4],
        [8],
        [6],
        [4]]),
 array([[8, 7],
        [3, 7],
        [3, 6],
        [5, 4]]),
 array([[2],
        [8],
        [4],
        [8]])]

In [124]:
np.hsplit(F,[1,3])[0] # 0--1,1-3

array([[4],
       [8],
       [6],
       [4]])

In [125]:
np.hsplit(F,[1,3])[1]

array([[8, 7],
       [3, 7],
       [3, 6],
       [5, 4]])

In [126]:
np.vsplit(F,2)

[array([[4, 8, 7, 2],
        [8, 3, 7, 8]]),
 array([[6, 3, 6, 4],
        [4, 5, 4, 8]])]

In [127]:
np.vsplit(F,[1,3])

[array([[4, 8, 7, 2]]),
 array([[8, 3, 7, 8],
        [6, 3, 6, 4]]),
 array([[4, 5, 4, 8]])]

In [134]:
F = np.arange(1,5)

In [135]:
F

array([1, 2, 3, 4])

In [140]:
np.where(F<4,["T","T","T","T"],["F","F","F","F"])

array(['T', 'T', 'T', 'F'], dtype='<U1')

In [143]:
np.where(F<4,["F","F","F","F"],["T","T","T","T"])

array(['F', 'F', 'F', 'T'], dtype='<U1')

In [145]:
np.where(F < 4, F, "Not Printed")

array(['1', '2', '3', 'Not Printed'], dtype='<U11')

In [146]:
import pandas as pd

In [147]:
D = np.array([1,2,3,4,5])
p = pd.Series(D)

In [148]:
p

0    1
1    2
2    3
3    4
4    5
dtype: int32

1

In [150]:
a = np.arange(1,11)
b = np.arange(81,91)

a = pd.Series(a)
b = pd.Series(b)


In [151]:
a = pd.Series(a)
b = pd.Series(b)

In [153]:
pd.DataFrame({"col1":a,"col2":b})

col1  col2
0     1    81
1     2    82
2     3    83
3     4    84
4     5    85
5     6    86
6     7    87
7     8    88
8     9    89
9    10    90

In [ ]:
# from list
# from tuple
# from dict