#### 21/08/2023

In [1]:
!pip install numpy

#when you are installing a library 

In [2]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
# 3 Dimentional array acess 2nd row 3 element

In [4]:
a = np.array([1,2,3],ndmin = 3)
print(a.shape)
print(a)

(1, 1, 3)
[[[1 2 3]]]


In [5]:
a

array([[[1, 2, 3]]])

In [6]:
a = np.array([[[1,2,3],[34,45,56],[54,55,67]]])
print(a.shape)
print(a)

(1, 3, 3)
[[[ 1  2  3]
  [34 45 56]
  [54 55 67]]]


In [7]:
# 1D array

In [8]:
y = [1,2,3,4]
for i in range(1,len(y)):
     y[i] = i*4
print(y)

[1, 4, 8, 12]


In [9]:
y=np.array([1,2,3,4])
y=y*4
print(y)

[ 4  8 12 16]


In [10]:
#boolean indexing
#to filter out
#consider subsets

In [11]:
a = np.arange(20,40,2)
print(a)

[20 22 24 26 28 30 32 34 36 38]


In [12]:
import random 
random.randint(10,20)

13

In [13]:
my_table = np.random.randint(10,40,size = (10,10))
print(my_table)

[[21 19 13 22 37 14 15 34 14 37]
 [12 36 12 36 25 35 10 32 29 12]
 [22 33 11 15 32 17 10 15 33 16]
 [10 26 39 12 35 26 15 16 15 10]
 [33 23 31 37 22 11 35 28 34 28]
 [10 17 10 21 26 26 22 13 21 15]
 [14 14 27 33 35 10 32 10 19 23]
 [28 19 15 31 32 23 36 11 12 16]
 [20 39 39 14 22 12 20 33 13 28]
 [28 31 33 12 22 10 19 27 15 33]]


In [14]:
my_table[7:10,7:10]#last 3 rows 3 columns

array([[11, 12, 16],
       [33, 13, 28],
       [27, 15, 33]])

In [15]:
my_table[0:10,3]#ftsr column acessed

array([22, 36, 15, 12, 37, 21, 33, 31, 14, 12])

In [16]:
my_table[:,3]

array([22, 36, 15, 12, 37, 21, 33, 31, 14, 12])

In [17]:
# Lets create a 2dimentional array with integers


table1 = np.random.randint(10,20,size = (10,8))
print(table1)
print(table1.shape) 

[[10 11 13 13 17 14 14 10]
 [12 13 16 12 17 19 19 17]
 [13 12 17 15 13 18 13 11]
 [16 13 14 19 19 11 14 18]
 [13 18 19 11 14 11 18 12]
 [16 17 10 13 14 15 18 17]
 [12 14 15 14 10 12 19 12]
 [10 19 17 16 19 14 10 13]
 [12 15 10 10 10 14 18 18]
 [12 12 18 12 18 16 18 11]]
(10, 8)


In [18]:
print(np.ndarray.flatten(table1))

[10 11 13 13 17 14 14 10 12 13 16 12 17 19 19 17 13 12 17 15 13 18 13 11
 16 13 14 19 19 11 14 18 13 18 19 11 14 11 18 12 16 17 10 13 14 15 18 17
 12 14 15 14 10 12 19 12 10 19 17 16 19 14 10 13 12 15 10 10 10 14 18 18
 12 12 18 12 18 16 18 11]


In [19]:
table2 =  np.random.randint(1,10,size = (10,8))
print(table2)
print(np.ndarray.flatten(table2))

[[2 2 4 1 2 4 9 1]
 [3 1 2 8 5 5 9 2]
 [2 1 8 7 9 2 4 9]
 [9 5 8 4 7 1 1 5]
 [6 3 3 5 9 4 1 9]
 [1 4 2 6 4 7 9 3]
 [2 3 3 1 4 4 4 6]
 [7 5 9 4 8 2 9 3]
 [8 2 2 7 8 9 3 8]
 [1 9 7 1 2 2 3 6]]
[2 2 4 1 2 4 9 1 3 1 2 8 5 5 9 2 2 1 8 7 9 2 4 9 9 5 8 4 7 1 1 5 6 3 3 5 9
 4 1 9 1 4 2 6 4 7 9 3 2 3 3 1 4 4 4 6 7 5 9 4 8 2 9 3 8 2 2 7 8 9 3 8 1 9
 7 1 2 2 3 6]


In [20]:
 table2 =  np.random.randint(1,27,size = (3,3,3))
print(table2)
print(np.ndarray.flatten(table2))

[[[ 3  3  3]
  [16 25 25]
  [13  6 11]]

 [[ 7 23 21]
  [ 8 14  9]
  [13 18 21]]

 [[22  7 20]
  [ 4  1  8]
  [16  4  9]]]
[ 3  3  3 16 25 25 13  6 11  7 23 21  8 14  9 13 18 21 22  7 20  4  1  8
 16  4  9]


In [21]:
import numpy as np

A = np.array([7,8,32,45,64,92],dtype = "int64")

np.std(A)
np.var(A)

911.888888888889

In [22]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6])
c=np.array([93,48,102,111])
print(a)
print(b)
print(c)
np.corrcoef([a,c])

[1 2 3 4 5]
[3 4 5 6]
[ 93  48 102 111]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
np.corrcoef([a,b])

In [ ]:
np.corrcoef([a,c])

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
a.shape

In [ ]:
# Accessing the element in the 2nd row, 3rd column of the first (and only) layer
# Note: Indexing starts at 0, so 2nd row is index 1 and 3rd element is index 2
a[0, 1, 2] = "text"

print(a)


In [ ]:
y=[1,2,3,4]
for i in range(0,len(y)):
    y[i] = y[i]*4
    print(y[i])

In [ ]:
z=np.array([1,2,3,4])
z = z*4
print(z)

In [ ]:
h=np.array([1,2,3,4,5,6,7,8,9,10])
print(h)
print(h.shape)
print(h.ndim)


In [23]:
!pip install numpy

#when you are installing a library 

In [25]:
!python --version

Python 3.11.5


In [26]:
import numpy as np
print(np.__version__)

1.24.3
